### ISSUE TITLE
Redirecting methods in System libraries

### ISSUE THREAD

**Issue by mnns** [spinico/MethodRedirect#2]
Hi!

I'm trying to redirect System.IO.File.ReadAllText to my own method.
I tried using the examples but getting a System.MissingMethodException: 'Cannot create an abstract class.' while trying to initiate the dynamic variable on:

        var scenario = (System.IO.File)Activator.CreateInstance(Scenario_Type);

How can this be done?
Thanks

**Comment by spinico** [comment]
Make sure that the Type parameter of the CreateInstance call can be instanciated, abstract class cannot.
