### ISSUE TITLE
2 bytes, which correspond to a maximum of 255 per type -> 2 bytes (16 bits) corresponds to a maximum number of 65536 slots per type

### ISSUE THREAD

**Issue by CaeruleusAqua** [spinico/MethodRedirect#4]
Unfortunately your code does not work for me.
I have now debugged around and come to the conclusion that something is wrong with the slot. 

For fun I have now simply searched for the address after the ms address and come to a much larger slot number (288 instead of 152).
An with these values correct method gets called afterwards, but the code ist dangerous :-(

```
                // Get the virtual method address relative to the first method slot
                address = ms + (slot2 * IntPtr.Size);  // slot is 152 here
                int slot = 0;
                while (true)
                {
                    
                    address = ms + (slot * IntPtr.Size); 
                    if (Marshal.ReadIntPtr(address) == solution)
                    {
                        break; //slot ist 288 here
                    }
                    slot += 1;
                }
```
Any hints?

PS:
2 bytes, which correspond to a maximum of 255 per type -> 2 bytes (16 bits) corresponds to a maximum number of 65536 slots per type

**Comment by CaeruleusAqua** [comment]
BTW:
`const ushort SLOT_NUMBER_MASK = 0xfff; // 3 bytes mask`

is not an 3 byte mask

`const ushort SLOT_NUMBER_MASK = 0xffff; // 2 bytes mask`

is probably correct, but does not solve my problem..

**Comment by spinico** [comment]
I must have been tired when I wrote the comments, I should have specified the number of bits masked instead. 

To clarify, an 8 bits (0xff) mask was initially used to obtain the slot number value, which was incorrect when looking at  the **MethodDesc** structure, so it was changed to a 16 bits (0xffff) mask. Then I remember having issues with the slot number value being too large in some cases and so the mask was adjusted to 12 bits (0xfff), but this may be an incorrect interpretation of how it actually works.

I'll have to take some time to review this and I'll revise the code comments accordingly. Do you have a failing test case that you could share ?

Note: it is possible to show more detailed output in the console by setting the `verbose` parameter of the `RedirectTo` method to `true`.

**Comment by CaeruleusAqua** [comment]
I have already seen the verbose parameter. 

I can't provide a code example because I'm trying to override a function in proprietary decompiled code. But I can see if I can reconstruct a similar case.
