### ISSUE TITLE
Replacing methods with lambdas

### ISSUE THREAD

**Issue by jorgeleo** [spinico/MethodRedirect#5]
I would like to have a syntax like this:

```csharp
      origin.RedirectToL((int x) =>
      {
        Console.WriteLine("Lambda " + x.ToString());
        return 1;
      });
```

Assuming that the lambda signature matches the signature of the origin method, I added this to the extensions:

```csharp
    public static MethodOperation RedirectToL<T, R>(this MethodInfo origin, Func<T, R> target, bool verbose = false)
      => RedirectTo(origin, target.Method);
```

Th calling into the lambda works, the returning value works. but the parameter x is taking a really weird value, much different than the one that is passing.

Any ideas how to make the lambda syntax work?

**Comment by spinico** [comment]
I added a scenario to test method redirection to a simple lambda expression. I noticed that the origin method should be declared `virtual` otherwise the redirection to the lambda expression would not work.

**Comment by jorgeleo** [comment]
Thank you, nice to know. The methods I am replacing are not necessarily virtual. is ok, It is more "Wordy", but it still can be done with methods
